"""Structured contracts shared by the lab's use-case modules."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class CompanyResearchBrief(BaseModel):
    """Bounded output for the company research agent."""

    company_name: str
    business_summary: str
    customer_signals: list[str] = Field(default_factory=list)
    risk_signals: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)


class SupportCase(BaseModel):
    """Synthetic case event used by TriageX and case-management examples."""

    case_id: str = ""
    source: str = "aws"
    account_id: str = ""
    customer_tier: str = "standard"
    severity: str = "medium"
    summary: str = ""

    def missing_fields(self) -> list[str]:
        """Return fields required before the case-management Agent can run."""
        return [
            field_name
            for field_name in ("case_id", "source", "account_id", "summary")
            if not getattr(self, field_name).strip()
        ]


class GitHubTriageCandidate(BaseModel):
    """Evidence extracted from one GitHub issue or pull request."""

    kind: Literal["issue", "pull_request", "unknown"]
    number: int
    title: str
    body: str = ""
    url: str
    state: str = "unknown"
    labels: list[str] = Field(default_factory=list)
    has_problem_statement: bool = False
    has_desired_outcome: bool = False
    has_supporting_evidence: bool = False
    has_test_evidence: bool = False


class CaseProcessingPlan(BaseModel):
    """Structured output created by the case-management Agent."""

    case_id: str
    customer_summary: str
    recommended_owner: str
    next_actions: list[str]
    missing_context: list[str] = Field(default_factory=list)


class LeadEmail(BaseModel):
    """Draft generated by the lead-outreach Agent."""

    subject: str
    body: str
    call_to_action: str
    claims_used: list[str] = Field(default_factory=list)


class EmailEvaluation(BaseModel):
    """Content-quality evaluation performed before human review."""

    score: int = Field(ge=0, le=100)
    passed: bool
    strengths: list[str] = Field(default_factory=list)
    issues: list[str] = Field(default_factory=list)
